export interface ServiceData {
  slug: string;
  title: string;
  tagline: string;
  description: string;
  icon: string;
  accentColor: string;
  features: string[];
  process: { step: number; title: string; desc: string }[];
  metaTitle: string;
  metaDesc: string;
}

export const servicesData: Record<string, ServiceData> = {
  "full-stack-development": {
    slug: "full-stack-development",
    title: "Full-Stack Development",
    tagline: "End-to-end web applications built to scale",
    description: "We design, build, and deploy high-performance web applications using modern technologies like Next.js, React, Node.js, and cloud-native infrastructure. From simple dashboards to complex SaaS platforms — we handle the full stack.",
    icon: "Code2",
    accentColor: "#7c3aed",
    features: [
      "Custom web application development",
      "RESTful & GraphQL APIs",
      "Database design & optimization (PostgreSQL, MySQL, D1)",
      "Cloud deployment (Cloudflare, Vercel, AWS)",
      "Performance & Core Web Vitals optimization",
      "Third-party integrations & payment gateways",
      "Real-time features (WebSockets, SSE)",
      "Authentication & authorization systems",
    ],
    process: [
      { step: 1, title: "Discovery", desc: "We understand your goals, users, and technical requirements through structured workshops." },
      { step: 2, title: "Architecture", desc: "We design the system architecture, choose the right stack, and map the data models." },
      { step: 3, title: "Development", desc: "Agile sprints with weekly demos, clear milestones, and constant communication." },
      { step: 4, title: "Testing", desc: "End-to-end testing, security audits, performance tuning, and accessibility review." },
      { step: 5, title: "Launch", desc: "Deployment to production, monitoring setup, CI/CD pipelines, and team handover." },
    ],
    metaTitle: "Full-Stack Development Services | The Web Start",
    metaDesc: "Custom web applications, APIs, and cloud deployments using Next.js, React, Node.js and modern infrastructure.",
  },
  "wordpress-development": {
    slug: "wordpress-development",
    title: "WordPress Development",
    tagline: "Powerful WordPress solutions for every business",
    description: "From custom themes to complex plugins and WooCommerce stores, we deliver WordPress solutions that are fast, secure, and easy to manage. No page builders — pure, clean, maintainable code.",
    icon: "Globe",
    accentColor: "#3b82f6",
    features: [
      "Custom WordPress theme development",
      "Plugin development & customization",
      "WooCommerce store setup & optimization",
      "Performance & PageSpeed optimization",
      "Security hardening & malware cleanup",
      "Migration from other platforms",
      "Multisite network setup",
      "Headless WordPress with Next.js frontend",
    ],
    process: [
      { step: 1, title: "Planning", desc: "Site map, wireframes, content strategy, and plugin requirements definition." },
      { step: 2, title: "Design", desc: "Custom design aligned with your brand identity and conversion goals." },
      { step: 3, title: "Development", desc: "Clean, standards-compliant WordPress code. No bloated builders." },
      { step: 4, title: "Content & SEO", desc: "Content migration, on-page SEO setup, schema markup, and sitemap." },
      { step: 5, title: "Launch", desc: "Staging test, go-live, CDN setup, and caching configuration." },
    ],
    metaTitle: "WordPress Development Services | The Web Start",
    metaDesc: "Custom WordPress themes, plugins, WooCommerce stores, and headless WordPress solutions built for performance.",
  },
  "ui-ux-design": {
    slug: "ui-ux-design",
    title: "UI/UX Design",
    tagline: "Interfaces that users love and businesses trust",
    description: "We create intuitive, beautiful digital experiences through research-driven design, prototyping, and iterative user testing. Every pixel has a purpose.",
    icon: "Palette",
    accentColor: "#ec4899",
    features: [
      "User research & persona creation",
      "Information architecture & user flows",
      "Wireframing & interactive prototyping",
      "High-fidelity UI design in Figma",
      "Design systems & component libraries",
      "Usability testing & accessibility (WCAG 2.1)",
      "Motion design & micro-interactions",
      "Developer handoff with Figma annotations",
    ],
    process: [
      { step: 1, title: "Research", desc: "User interviews, competitor analysis, and heuristic evaluation of the current product." },
      { step: 2, title: "Strategy", desc: "Information architecture, user journey maps, and experience principles definition." },
      { step: 3, title: "Wireframes", desc: "Low-fidelity wireframes for rapid iteration and stakeholder alignment." },
      { step: 4, title: "Visual Design", desc: "High-fidelity mockups with your brand identity, animations, and micro-interactions." },
      { step: 5, title: "Handoff", desc: "Annotated Figma files, design tokens, and a comprehensive design system document." },
    ],
    metaTitle: "UI/UX Design Services | The Web Start",
    metaDesc: "User-centred UI/UX design — wireframes, prototyping, high-fidelity Figma design, and design systems.",
  },
  "seo": {
    slug: "seo",
    title: "SEO",
    tagline: "Rank higher. Get found. Grow organically.",
    description: "Our data-driven SEO strategies combine technical optimization, content strategy, and authority building to drive sustainable organic growth that compounds over time.",
    icon: "TrendingUp",
    accentColor: "#10b981",
    features: [
      "Comprehensive technical SEO audits",
      "Keyword research & intent mapping",
      "On-page optimisation (titles, meta, schema)",
      "Core Web Vitals & page speed optimization",
      "Content strategy & SEO writing",
      "Link building & digital PR",
      "Local SEO & Google Business Profile",
      "Monthly reporting & rank tracking",
    ],
    process: [
      { step: 1, title: "Audit", desc: "Deep technical, content, and backlink audit to identify every growth opportunity." },
      { step: 2, title: "Strategy", desc: "Keyword mapping, topical authority planning, and competitor gap analysis." },
      { step: 3, title: "Optimization", desc: "Technical fixes, on-page improvements, and Core Web Vitals resolution." },
      { step: 4, title: "Content", desc: "Creation of SEO-optimised content targeting high-intent keywords." },
      { step: 5, title: "Monitor", desc: "Ongoing rank tracking, backlink monitoring, and monthly strategy refinement." },
    ],
    metaTitle: "SEO Services | The Web Start",
    metaDesc: "Data-driven SEO — technical audits, keyword strategy, content, link building, and monthly reporting.",
  },
  "social-media-marketing": {
    slug: "social-media-marketing",
    title: "Social Media Marketing",
    tagline: "Build your brand. Engage your audience.",
    description: "We manage and grow your social media presence across all major platforms with strategic content, community management, and paid campaigns that drive measurable results.",
    icon: "Share2",
    accentColor: "#f97316",
    features: [
      "Social media audit & strategy",
      "Content creation (graphics, reels, carousels)",
      "Content calendar & scheduling",
      "Community management & DM handling",
      "Paid social campaigns (Meta, LinkedIn, Google)",
      "Influencer outreach & partnerships",
      "Hashtag research & trend monitoring",
      "Monthly analytics & performance reports",
    ],
    process: [
      { step: 1, title: "Audit", desc: "Review of your existing presence, audience, and competitor benchmarking." },
      { step: 2, title: "Strategy", desc: "Platform selection, content pillars, brand voice, and posting cadence." },
      { step: 3, title: "Content", desc: "High-quality visual design and copywriting tailored to each platform." },
      { step: 4, title: "Publish & Engage", desc: "Scheduled posting, comment management, and community building." },
      { step: 5, title: "Report", desc: "Monthly performance reviews with reach, engagement, and growth metrics." },
    ],
    metaTitle: "Social Media Marketing Services | The Web Start",
    metaDesc: "Strategic social media management — content creation, community management, and paid campaigns.",
  },
  "branding": {
    slug: "branding",
    title: "Branding",
    tagline: "Your identity, crafted to stand out and last",
    description: "From brand strategy to visual identity, we create cohesive brand systems that communicate your values, differentiate you from competitors, and resonate deeply with your audience.",
    icon: "Sparkles",
    accentColor: "#8b5cf6",
    features: [
      "Brand strategy & positioning",
      "Logo design & brand mark creation",
      "Colour palette & typography system",
      "Brand guidelines & style guide",
      "Business stationery & collateral",
      "Brand voice & messaging framework",
      "Social media brand kit",
      "Brand refresh & rebranding",
    ],
    process: [
      { step: 1, title: "Discovery", desc: "Brand workshop to understand your vision, values, target audience, and market position." },
      { step: 2, title: "Research", desc: "Competitor analysis, trend research, and market positioning map." },
      { step: 3, title: "Concepts", desc: "Three creative directions presented with rationale and mood boards." },
      { step: 4, title: "Refinement", desc: "Iterative refinement of the chosen direction based on your feedback." },
      { step: 5, title: "Delivery", desc: "Complete brand guidelines PDF, all source files, and asset export package." },
    ],
    metaTitle: "Branding Services | The Web Start",
    metaDesc: "Complete brand identity — strategy, logo design, colour systems, typography, and brand guidelines.",
  },
};
