name = "the-web-start"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "thewebstart-db"
database_id = "a5b678c4-7951-44a5-a924-7f79c5ce3463"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "thewebstart-images"

[vars]
NEXT_PUBLIC_SITE_URL = "https://thewebstart.in"
